# Generated by Django 2.1.2 on 2018-10-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_models',
        ),
    ]
